presubmits:
  - name: presubmit-nephio-go-test
    decorate: true
    run_if_changed: "(\\.go|Makefile)$"
    spec:
      containers:
      - image: nephio/gotests:1782782171367346176
        command:
        - make
        args:
        - ci-unit
  - name: presubmit-porch-e2e
    decorate: true
    optional: true
    run_if_changed: "(\\.go|Makefile)$"
    spec:
      containers:
      - image: nephio/gotests:1782782171367346176
        command:
        - make
        args:
        - ci-test-porch
