presubmits:
  - name: presubmit-nephio-go-test
    decorate: true
    run_if_changed: "(\\.go|Makefile|\\.mk)$"
    spec:
      containers:
      - image: nephio/gotests:1782782171367346176
        command:
        - make
        args:
        - ci-unit
postsubmits:
  - name: build-push-porch-server-dev-image
    cluster: default
    always_run: true
    branches:
    - "main"
    annotations:
      description: Build and Push Dev Image to DockerHub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 1
    extra_refs:
    - org: nephio-project
      repo: porch
      base_ref: main
      path_alias: "porch_build/porch"
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=/home/prow/go/src/porch_build/ --dockerfile=porch/build/Dockerfile --destination=nephio/porch-server:${PULL_BASE_REF} --destination=nephio/porch-server:latest
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json


  - name: build-push-porch-controllers-dev-image
    cluster: default
    always_run: true
    branches:
    - "main"
    annotations:
      description: Build and Push Dev Image to DockerHub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 1
    extra_refs:
    - org: nephio-project
      repo: porch
      base_ref: main
      path_alias: "porch_build/porch"
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=/home/prow/go/src/porch_build/ --dockerfile=porch/controllers/Dockerfile --destination=nephio/porch-controllers:${PULL_BASE_REF} --destination=nephio/porch-controllers:latest
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json


  - name: build-push-porch-function-runner-dev-image
    cluster: default
    always_run: true
    branches:
    - "main"
    annotations:
      description: Build and Push Dev Image to DockerHub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 1
    extra_refs:
    - org: nephio-project
      repo: porch
      base_ref: main
      path_alias: "porch_build/porch"
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=/home/prow/go/src/porch_build/ --dockerfile=porch/func/Dockerfile --destination=nephio/porch-function-runner:${PULL_BASE_REF} --destination=nephio/porch-function-runner:latest
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json


  - name: build-push-porch-wrapper-server-dev-image
    cluster: default
    always_run: true
    branches:
    - "main"
    annotations:
      description: Build and Push Dev Image to DockerHub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 1
    extra_refs:
    - org: nephio-project
      repo: porch
      base_ref: main
      path_alias: "porch_build/porch"
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=/home/prow/go/src/porch_build/ --dockerfile=porch/func/Dockerfile-wrapperserver --destination=nephio/porch-wrapper-server:${PULL_BASE_REF} --destination=nephio/porch-wrapper-server:latest
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json

