# Copyright 2022-2025 The kpt and Nephio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ServiceAccount
apiVersion: v1
metadata:
  name: porch-fn-runner
  namespace: porch-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: function-runner
  namespace: porch-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: function-runner
  template:
    metadata:
      labels:
        app: function-runner
    spec:
      serviceAccountName: porch-fn-runner
      containers:
        - name: function-runner
          image: docker.io/nephio/porch-function-runner:latest
          imagePullPolicy: IfNotPresent
          command:
            - /server
            - --config=/config.yaml
            - --functions=/functions
            - --pod-namespace=porch-fn-system
            - --max-request-body-size=6291456 # Keep this in sync with porch-server's corresponding argument
          env:
            - name: WRAPPER_SERVER_IMAGE
              value: docker.io/nephio/porch-wrapper-server:latest
          ports:
            - containerPort: 9445
          # Add grpc readiness probe to ensure the cache is ready
          readinessProbe:
            exec:
              command:
                - /grpc-health-probe
                - -addr
                - localhost:9445
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
          volumeMounts:
            - mountPath: /pod-cache-config
              name: pod-cache-config-volume
      volumes:
        - name: pod-cache-config-volume
          configMap:
            name: pod-cache-config

---
apiVersion: v1
kind: Service
metadata:
  name: function-runner
  namespace: porch-system
spec:
  selector:
    app: function-runner
  ports:
    - port: 9445
      protocol: TCP
      targetPort: 9445

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-cache-config
  namespace: porch-system
data:
  pod-cache-config.yaml: |
    ghcr.io/kptdev/krm-functions-catalog/apply-replacements:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/apply-setters:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/create-setters:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/ensure-name-substring:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/gatekeeper:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/kubeval:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/search-replace:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/set-annotations:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/set-enforcement-action:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/set-image:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/set-labels:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/set-namespace:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/starlark:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/upsert-resource:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/enable-gcp-services:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/export-terraform:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/generate-folders:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/remove-local-config-resources:latest: 30m
    ghcr.io/kptdev/krm-functions-catalog/set-project-id:latest: 30m
