// Code generated by mockery v2.53.3. DO NOT EDIT.

package cachetypes

import (
	context "context"

	repository "github.com/nephio-project/porch/pkg/repository"
	mock "github.com/stretchr/testify/mock"

	watch "k8s.io/apimachinery/pkg/watch"
)

// MockRepoPRChangeNotifier is an autogenerated mock type for the RepoPRChangeNotifier type
type MockRepoPRChangeNotifier struct {
	mock.Mock
}

type MockRepoPRChangeNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoPRChangeNotifier) EXPECT() *MockRepoPRChangeNotifier_Expecter {
	return &MockRepoPRChangeNotifier_Expecter{mock: &_m.Mock}
}

// NotifyPackageRevisionChange provides a mock function with given fields: ctx, eventType, obj
func (_m *MockRepoPRChangeNotifier) NotifyPackageRevisionChange(ctx context.Context, eventType watch.EventType, obj repository.PackageRevision) int {
	ret := _m.Called(ctx, eventType, obj)

	if len(ret) == 0 {
		panic("no return value specified for NotifyPackageRevisionChange")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, watch.EventType, repository.PackageRevision) int); ok {
		r0 = rf(ctx, eventType, obj)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyPackageRevisionChange'
type MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call struct {
	*mock.Call
}

// NotifyPackageRevisionChange is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType watch.EventType
//   - obj repository.PackageRevision
func (_e *MockRepoPRChangeNotifier_Expecter) NotifyPackageRevisionChange(ctx interface{}, eventType interface{}, obj interface{}) *MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call {
	return &MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call{Call: _e.mock.On("NotifyPackageRevisionChange", ctx, eventType, obj)}
}

func (_c *MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call) Run(run func(ctx context.Context, eventType watch.EventType, obj repository.PackageRevision)) *MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(watch.EventType), args[2].(repository.PackageRevision))
	})
	return _c
}

func (_c *MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call) Return(_a0 int) *MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call) RunAndReturn(run func(context.Context, watch.EventType, repository.PackageRevision) int) *MockRepoPRChangeNotifier_NotifyPackageRevisionChange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepoPRChangeNotifier creates a new instance of MockRepoPRChangeNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoPRChangeNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoPRChangeNotifier {
	mock := &MockRepoPRChangeNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
